vehicle_rental/cars/urls.py
from django.urls import path
from .views import CarsByCategory, CarsByClass, CarDetailView

app_name = 'cars'

urlpatterns = [
    path('category/<int:pk>', CarsByCategory.as_view(), name='category'),
    path('class/<int:pk>', CarsByClass.as_view(), name='class'),
    path('car/<int:pk>', CarDetailView.as_view(), name='detail'),
]

vehicle_rental/custom_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (CustomUserLoginView, CustomUserCreationView, LogoutView, CustomUserProfileView,
                    verify_email, verify_email_success, verify_email_confirm, verify_email_complete, change_password)


app_name = 'custom_auth'

urlpatterns = [
    path('login/', CustomUserLoginView.as_view(), name='login'),
    path('signup/', CustomUserCreationView.as_view(), name='signup'),
    path('logout/', LogoutView, name='logout'),

    path('change_password/', change_password, name='change_password'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(), name='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', CustomUserProfileView.as_view(), name='profile'),

    path('verify_email/', verify_email, name='verify_email'),
    path('verify_email/success/', verify_email_success, name='verify_email_success'),
    path('verify_email_confirm/<uidb64>/<token>/', verify_email_confirm, name='verify_email_confirm'),
    path('verify_email/complete/', verify_email_complete, name='verify_email_complete'),
]

vehicle_rental/main/urls.py
from django.urls import path
from .views import home, CarBook, payment_checkout, contact, bookings, protection_details


app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('bookings/', bookings, name='bookings'),

    path('book_car/<int:pk>/', CarBook.as_view(), name='book_car'),
    path('book_car/car_payment/<int:pk>', payment_checkout, name='car_payment'),

    path('protection_info/', protection_details, name='protection_details')
]

vehicle_rental/vehicle_rental/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('auth/', include('custom_auth.urls')),
    path('payment/', include('payment.urls')),
    path('cars/', include('cars.urls')),

    #path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.custom_404'

vehicle_rental/custom_auth/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username')

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'lq2-form-control lq2-width-100%', 'id': 'input-email',
                                             'placeholder': "email@myemail.com"}),
            'username': forms.TextInput(attrs={'class': 'lq2-form-control lq2-width-100%', 'id': 'input-username',
                                               'placeholder': 'username'}),
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username')


class CustomUserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'lq2-form-control lq2-width-100%',
                                                            'id': 'input-email', 'placeholder': "email@myemail.com"}))

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'lq2-form-control lq2-width-100%',
                                                                 'id': 'input-password', 'placeholder': 'password'}))

vehicle_rental/main/forms.py
from django import forms
from .models import CarBooking
from phone_field import PhoneFormField, PhoneWidget


class CarBookingForm(forms.ModelForm):
    class Meta:
        model = CarBooking

        fields = ['booked_from', 'booked_to', 'milage',
                  'protection', 'additional_driver', 'infant_seat',
                  'baby_stroller', 'fuel_service', 'customer_name',
                  'customer_surname', 'customer_phone', 'country',
                  'city', 'state', 'zip', 'street', 'other_information'
                  ]

        widgets = {
            'customer_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'firstName'}),
            'customer_surname': forms.TextInput(attrs={'class': 'form-control', 'id': 'lastName'}),
            'customer_phone': PhoneWidget(attrs={'class': 'customer_phone_input', 'id': 'customer_phone'}),

            'country': forms.TextInput(attrs={'class': 'form-control', 'id': 'country'}),
            'city': forms.TextInput(attrs={'class': 'form-control', 'id': 'city'}),
            'state': forms.TextInput(attrs={'class': 'form-control', 'id': 'state'}),
            'zip': forms.TextInput(attrs={'class': 'form-control', 'id': 'zip'}),
            'street': forms.TextInput(attrs={'class': 'form-control', 'id': 'street'}),

            'booked_from': forms.DateInput(attrs={'class': 'date_input', 'id': 'booked_from', 'type': 'date'}),
            'booked_to': forms.DateInput(attrs={'class': 'date_input', 'id': 'booked_to',  'type': 'date'}),

            'additional_driver': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'additional_driver'}),
            'infant_seat': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'infant_seat'}),
            'baby_stroller': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'baby_stroller'}),
            'fuel_service': forms.CheckboxInput(attrs={'class': 'form-check-input', 'id': 'fuel_service'}),

            'other_information': forms.TextInput(attrs={'class': 'form-control', 'id': 'other_information'})
        }

vehicle_rental/main/views.py
import datetime
from datetime import date

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import FormView

from .models import CarBooking, Car
from .forms import CarBookingForm

from cars.models import Category, Class

from payment.views import payment_checkout


def contact(request):
    return render(request, 'main/contact.html')


def protection_details(request):
    return render(request, 'main/protection_details.html')


@login_required
def bookings(request):
    data = {}
    for booking in CarBooking.objects.filter(customer=request.user):
        if booking.payment_success:
            data[booking] = (booking.booked_to - booking.booked_from).days * booking.car.price + booking.car.deposit

            if booking.additional_driver:
                data[booking] += 50
            elif booking.infant_seat:
                data[booking] += 30
            elif booking.baby_stroller:
                data[booking] += 30
            elif booking.fuel_service:
                data[booking] += 40

            if booking.protection == 'MaxE':
                data[booking] += 300
            elif booking.protection == 'RedE':
                data[booking] += 150

    context = {
        'data': data,
    }
    return render(request, 'main/user_bookings.html', context)


def home(request):
    cars = Car.objects.all()
    categories = Category.objects.all()
    classes = Class.objects.all()

    if request.user.is_authenticated:
        bookings = CarBooking.objects.filter(customer=request.user)
        for book in bookings:
            if not book.payment_success:
                book.delete()

    location_input = request.GET.get('location') or ''
    booked_from_input = request.GET.get('booked_from') or ''
    booked_to_input = request.GET.get('booked_to') or ''

    if request.GET:
        return search_output(request, location_input, booked_from_input, booked_to_input)

    context = {
        'cars': cars,
        'categories': categories,
        'classes': classes,
    }
    return render(request, 'main/home.html', context)


def search_output(request, location_input, booked_from_input, booked_to_input):
    cars = []
    not_found_message = ''
    error_message = ''

    if not location_input and not booked_from_input and not booked_to_input:
        cars = Car.objects.all()

    elif location_input and booked_from_input and booked_to_input:
        for car in Car.objects.filter(location__icontains=location_input):
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if not ((datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') < datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')
                         and datetime.datetime.strptime(booked_to_input, '%Y-%m-%d') < datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')) or
                        (datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') > datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d')
                         and datetime.datetime.strptime(booked_to_input, '%Y-%m-%d') > datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d'))):

                    flag = False
            if flag and booked_to_input > booked_from_input:
                cars.append(car)

    elif location_input and booked_from_input and not booked_to_input:
        for car in Car.objects.filter(location__icontains=location_input):
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if (datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d') >= datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') >=
                        datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')):
                    flag = False
            if flag:
                cars.append(car)

    elif location_input and not booked_from_input and booked_to_input:
        for car in Car.objects.filter(location__icontains=location_input):
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if (datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d') <= datetime.datetime.strptime(booked_to_input, '%Y-%m-%d') <=
                        datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')):
                    flag = False
            if flag:
                cars.append(car)

    elif location_input and not booked_from_input and not booked_to_input:
        cars = Car.objects.filter(location__icontains=location_input)

    elif not location_input and booked_from_input and booked_to_input:
        for car in Car.objects.all():
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if not ((datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') < datetime.datetime.strptime(
                        str(booking.booked_from), '%Y-%m-%d')
                         and datetime.datetime.strptime(booked_to_input, '%Y-%m-%d') < datetime.datetime.strptime(
                            str(booking.booked_from), '%Y-%m-%d')) or
                        (datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') > datetime.datetime.strptime(
                            str(booking.booked_to), '%Y-%m-%d')
                         and datetime.datetime.strptime(booked_to_input, '%Y-%m-%d') > datetime.datetime.strptime(
                                    str(booking.booked_to), '%Y-%m-%d'))):
                    flag = False
            if flag and booked_to_input > booked_from_input:
                cars.append(car)

    elif not location_input and booked_from_input and not booked_to_input:
        for car in Car.objects.all():
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if (datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d') >= datetime.datetime.strptime(booked_from_input, '%Y-%m-%d') >=
                        datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')):
                    flag = False
            if flag:
                cars.append(car)

    elif not location_input and not booked_from_input and booked_to_input:
        for car in Car.objects.all():
            flag = True
            for booking in CarBooking.objects.filter(car=car):
                if (datetime.datetime.strptime(str(booking.booked_to), '%Y-%m-%d') <= datetime.datetime.strptime(
                        booked_to_input, '%Y-%m-%d') <=
                        datetime.datetime.strptime(str(booking.booked_from), '%Y-%m-%d')):
                    flag = False
            if flag:
                cars.append(car)

    else:
        not_found_message = 'No cars matching your search criteria'

    if booked_from_input and booked_to_input:
        if (datetime.datetime.strptime(booked_from_input, '%Y-%m-%d')) >= (datetime.datetime.strptime(booked_to_input, '%Y-%m-%d')):
            error_message = 'Book from cannot be ahead of book to'
            return render(request, 'main/invalid_search.html', {'error_message': error_message})
        elif ((datetime.datetime.strptime(booked_from_input, '%Y-%m-%d')) < datetime.datetime.now()
              or (datetime.datetime.strptime(booked_to_input, '%Y-%m-%d')) < datetime.datetime.now()):
            error_message = 'One of the entered dates are in the past'
            error_message_additional = '(Car have to be booked at least one day ahead)'
            return render(request, 'main/invalid_search.html',
                          {'error_message': error_message, 'error_message_additional': error_message_additional})
    elif booked_from_input:
        if (datetime.datetime.strptime(booked_from_input, '%Y-%m-%d')) < datetime.datetime.now():
            error_message = 'Book from is in the past'
            error_message_additional = '(You should book cars at least 1 day ahead)'
            return render(request, 'main/invalid_search.html',
                          {'error_message': error_message, 'error_message_additional': error_message_additional})
    elif booked_to_input:
        if (datetime.datetime.strptime(booked_to_input, '%Y-%m-%d')) < datetime.datetime.now():
            error_message = 'Book from is in the past'
            error_message_additional = '(You should book cars at least 1 day ahead)'
            return render(request, 'main/invalid_search.html',
                          {'error_message': error_message, 'error_message_additional': error_message_additional})

    context = {
        'cars': cars,
        'location': location_input,
        'booked_from': booked_from_input,
        'booked_to': booked_to_input,
        'not_found_message': not_found_message,
    }

    return render(request, 'main/search_cars.html', context)


class CarBook(LoginRequiredMixin, FormView):
    login_url = 'custom_auth:login'
    success_url = reverse_lazy('main:home')

    form_class = CarBookingForm
    template_name = 'main/book_car.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        car_id = self.request.GET.get('car_id')

        context['car'] = Car.objects.get(pk=car_id)

        return context

    def form_valid(self, form):
        car_id = self.request.GET.get('car_id')
        car = Car.objects.get(pk=car_id)

        booking = form.save(commit=False)
        bookings = CarBooking.objects.filter(car=car)

        if not self.request.user.email_is_verified:
            booking.delete()
            return redirect(reverse_lazy('main:home'))

        flag = True

        for book in bookings:
            if not ((booking.booked_from < book.booked_from and booking.booked_to < book.booked_from) or
                    (booking.booked_from > book.booked_to and booking.booked_to > book.booked_to)):

vehicle_rental/main/templates/main/home.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
Home Page
{% endblock title %}

{% block content %}
<div class="search-bar-container">
    <form method="get">
    <div class="container search-bar" style="background-image: url({% static 'images/website_photos/searchbar_background.png' %}); justify-content:center; display: flex;">
        <input type="text" id="form1" class="form-control" name="location" size="11" value="{{location_input}}" placeholder="Location" style="font-weight: 500"/>

        <label for="form1" style="color: white; font-weight: 800; font-size: 35">Book from</label>
        <input type="date" id="form2" class="form-control" name="booked_from" size="21" value="{{booked_from_input}}" placeholder="Book from"/>

        <label for="form1" style="color: white; font-weight: 800; font-size: 35">Book to</label>
        <input type="date" id="form3" class="form-control" name="booked_to" size="21" value="{{booked_to_input}}" placeholder="Book to"/>
        <button type="submit" id="form-submit" class="searchButton"><i class="fa fa-search"></i></button>
    </div>
</form>
</div>

<div class="container" style="height: 370px; display; flex;">
  <h2 class="mb-5" style="text-align: center; color: #ffbd00 ;font-weight: 350;">Deals & Products</h2>

  <div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-inner">

      <div class="carousel-item active">
        <a href="/" class="banner" aria-label="Shop now">
        <div class="banner__grid">
          <div aria-hidden="true">
            <figure class="banner__figure" style="background-image: url({% static 'images/website_photos/deal_1.jpeg' %});"></figure>
          </div>
          <div class="banner__text">
            <h2>Start your week in style!</h2>
            <p class="banner__link-wrapper">
              <span class="banner__link"><i>Great discount on a number of stylish cars.</i></span>
            </p>
          </div>
        </div>
        </a>
      </div>

      <div class="carousel-item">
        <a href="/" class="banner" aria-label="Shop now">
        <div class="banner__grid">
          <div aria-hidden="true">
            <figure class="banner__figure" style="background-image: url({% static 'images/website_photos/deal_2.jpeg' %});"></figure>
          </div>
          <div class="banner__text">
            <h2>Luxury, but for good price!</h2>
            <p class="banner__link-wrapper">
              <span class="banner__link"><i>Book now and save up to 25% on luxury cars.</i></span>
            </p>
          </div>
        </div>
        </a>
      </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Last</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>

  </div>
</div>



<div class="categories" style="background-image: url({% static 'images/website_photos/categories_background.jpeg' %})">
<div class="container">
    <h2 class="mb-5" style="text-align: center; color: #ffbd00 ;font-weight: 350;">Categories</h2>
    <div class="row row-cols-1 row-cols-md-3 g-3">
      {% for category in categories %}
      <div class="col category">
        <a style="text-decoration: none;" href="{% url 'cars:category' category.pk %}?category_id={{category.pk}}">
        <div class="card h-100" style="background: #212b37; opacity: 0.9;">
          <img style="opacity:1" src="{{ category.category_image.url }}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title" style="text-align: center; color: #ffbd00; font-size: 22px; font-weight: 350;">{{ category }}s</h5>
          </div>
        </div>
        </a>
      </div>
      {% endfor %}
    </div>
</div>
</div>

<!--<div class="container">-->
<!--    <h2 class="mb-5" style="text-align: center; color: #ffbd00 ;font-weight: 350;">Classes</h2>-->
<!--    {% for class in classes %}-->
<!--    <a id="class_item" href="{% url 'cars:class' class.pk %}?class_id={{ class.pk }}">{{class}}</a>-->
<!--    {% endfor %}-->
<!--</div>-->

<!--<div class="locations">-->
<!--<div class="container">-->
<!--    <h2 style="text-align: center">Locations</h2>-->
<!--</div>-->
<!--</div>-->

<section class="feature-v20 cd-padding-y-xl">
  <div class="cd-container cd-max-width-sm cd-margin-bottom-xl">
    <h1 class="cd-text-center" style="color: #ffbd00">Why us?</h1>
  </div>

  <div class="cd-container cd-max-width-adaptive-lg">
    <ul class="feature-v20__list">
      <li class="feature-v20__item">
        <figure class="feature-v20__icon-wrapper">
          <svg class="feature-v20__icon cd-icon" viewBox="0 0 24 24" aria-hidden="true">
            <g fill="currentColor">
              <path d="M21 10H3c-1.103 0-2-.897-2-2V5c0-1.103.897-2 2-2h18c1.103 0 2 .897 2 2v3c0 1.103-.897 2-2 2z"></path>
              <rect x="1" y="12" width="6" height="9" rx="2" ry="2" opacity=".4"></rect>
              <rect x="9" y="12" width="14" height="9" rx="2" ry="2" opacity=".4"></rect>
            </g>
          </svg>
        </figure>

        <div class="cd-text-center">
          <h4 class="cd-margin-bottom-2xs" style="color: #ffbd00">Broad fleet</h4>
          <p class="feature-v20__paragraph">A great number of varius cars all over the country.</p>
        </div>
      </li>

      <li class="feature-v20__item">
        <figure class="feature-v20__icon-wrapper">
          <svg class="feature-v20__icon cd-icon" viewBox="0 0 24 24" aria-hidden="true">
            <title>Galleries</title>
            <g fill="currentColor">
              <path d="M9 9H4c-1.103 0-2-.897-2-2V4c0-1.103.897-2 2-2h5c1.103 0 2 .897 2 2v3c0 1.103-.897 2-2 2z"></path>
              <rect x="2" y="11" width="9" height="11" rx="2" ry="2" opacity=".4"></rect>
              <path d="M20 22h-5c-1.103 0-2-.897-2-2v-3c0-1.103.897-2 2-2h5c1.103 0 2 .897 2 2v3c0 1.103-.897 2-2 2z"></path>
              <rect x="13" y="2" width="9" height="11" rx="2" ry="2" transform="rotate(180 17.5 7.5)" opacity=".4"></rect>
            </g>
          </svg>
        </figure>

        <div class="cd-text-center">
          <h4 class="cd-margin-bottom-2xs" style="color: #ffbd00">Affordable prices</h4>
          <p class="feature-v20__paragraph">We offer the best prices compared to our other rental companies.</p>
        </div>
      </li>

      <li class="feature-v20__item">
        <figure class="feature-v20__icon-wrapper">
          <svg class="feature-v20__icon cd-icon" viewBox="0 0 24 24" aria-hidden="true">
            <title>Animations</title>
            <g fill="currentColor">
              <circle cx="19" cy="9" r="5"></circle>
              <path d="M1 3.059A23.925 23.925 0 0 1 8 20c0-3.416 1.557-6.468 4-8.486" fill="none" opacity=".4" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"></path>
            </g>
          </svg>
        </figure>

        <div class="cd-text-center">
          <h4 class="cd-margin-bottom-2xs" style="color: #ffbd00">Great service</h4>
          <p class="feature-v20__paragraph">We treat our clients like kings, and we are ready to answer any question and help you whenever you want.</p>
        </div>
      </li>

      <li class="feature-v20__item">
        <figure class="feature-v20__icon-wrapper">
          <svg class="feature-v20__icon cd-icon" viewBox="0 0 24 24" aria-hidden="true">
            <title>UI Controls</title>
            <g fill="currentColor">
              <path d="M17.5 11h-11C4.019 11 2 8.981 2 6.5S4.019 2 6.5 2h11C19.981 2 22 4.019 22 6.5S19.981 11 17.5 11z" opacity=".4"></path>
              <circle cx="6.5" cy="6.5" r="4.5"></circle>
              <path d="M6.5 13h11c2.481 0 4.5 2.019 4.5 4.5S19.981 22 17.5 22h-11C4.019 22 2 19.981 2 17.5S4.019 13 6.5 13z" opacity=".4"></path>
              <circle cx="17.5" cy="17.5" r="4.5"></circle>
            </g>
          </svg>
        </figure>

        <div class="cd-text-center">
          <h4 class="cd-margin-bottom-2xs" style="color: #ffbd00">Accessibility</h4>
          <p class="feature-v20__paragraph">Book car online and take your car in one of our pick-up points.</p>
        </div>
      </li>
    </ul>
  </div>
</section>

{% endblock content %}