vehicle_rental/cars/urls.py
from django.urls import path
from .views import CarsByCategory, CarsByClass, CarDetailView

app_name = 'cars'

urlpatterns = [
    path('category/<int:pk>', CarsByCategory.as_view(), name='category'),
    path('class/<int:pk>', CarsByClass.as_view(), name='class'),
    path('car/<int:pk>', CarDetailView.as_view(), name='detail'),
]

vehicle_rental/custom_auth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (CustomUserLoginView, CustomUserCreationView, LogoutView, CustomUserProfileView,
                    verify_email, verify_email_success, verify_email_confirm, verify_email_complete, change_password)


app_name = 'custom_auth'

urlpatterns = [
    path('login/', CustomUserLoginView.as_view(), name='login'),
    path('signup/', CustomUserCreationView.as_view(), name='signup'),
    path('logout/', LogoutView, name='logout'),

    path('change_password/', change_password, name='change_password'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(), name='reset_password'),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('profile/', CustomUserProfileView.as_view(), name='profile'),

    path('verify_email/', verify_email, name='verify_email'),
    path('verify_email/success/', verify_email_success, name='verify_email_success'),
    path('verify_email_confirm/<uidb64>/<token>/', verify_email_confirm, name='verify_email_confirm'),
    path('verify_email/complete/', verify_email_complete, name='verify_email_complete'),
]

vehicle_rental/main/urls.py
from django.urls import path
from .views import home, CarBook, payment_checkout, contact, bookings, protection_details


app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('bookings/', bookings, name='bookings'),

    path('book_car/<int:pk>/', CarBook.as_view(), name='book_car'),
    path('book_car/car_payment/<int:pk>', payment_checkout, name='car_payment'),

    path('protection_info/', protection_details, name='protection_details')
]

vehicle_rental/vehicle_rental/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('auth/', include('custom_auth.urls')),
    path('payment/', include('payment.urls')),
    path('cars/', include('cars.urls')),

    #path('social-auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'main.views.custom_404'

vehicle_rental/custom_auth/models.py
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models
from django.utils import timezone

from .managers import CustomUserManager


class CustomUser(AbstractUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=127, unique=True)
    email_is_verified = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(blank=True, null=True)

    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    def get_full_name(self):
        return self.username

    def get_user_email(self):
        return self.email

vehicle_rental/custom_auth/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username')

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'lq2-form-control lq2-width-100%', 'id': 'input-email',
                                             'placeholder': "email@myemail.com"}),
            'username': forms.TextInput(attrs={'class': 'lq2-form-control lq2-width-100%', 'id': 'input-username',
                                               'placeholder': 'username'}),
        }


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username')


class CustomUserLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'lq2-form-control lq2-width-100%',
                                                            'id': 'input-email', 'placeholder': "email@myemail.com"}))

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'lq2-form-control lq2-width-100%',
                                                                 'id': 'input-password', 'placeholder': 'password'}))

vehicle_rental/custom_auth/views.py
from django.contrib.auth import login, authenticate, logout, forms, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.checks import messages
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import FormView, DetailView

from .forms import CustomUserCreationForm, CustomUserLoginForm
from .models import CustomUser
from main.models import CarBooking

from .tokens import account_activation_token
from django.contrib.auth.decorators import login_required


@login_required(redirect_field_name='main:home', login_url='custom_auth:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.Info('Your password was successfully updated!')
            return redirect('custom_auth:change_password')
        else:
            messages.Error('Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'custom_auth/change_password.html', {
        'form': form
    })


def verify_email_complete(request):
    request.user.email_is_verified = True
    request.user.is_active = True
    return render(request, 'custom_auth/verify_email_complete.html')


def verify_email_success(request):
    return render(request, 'custom_auth/verify_email_success.html')


def verify_email_confirm(request, uidb64, token):
    context = {
        'fail': '',
        'success': '',
    }
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)

    except(TypeError, ValueError, OverflowError):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.email_is_verified = True
        user.is_active = True
        user.save()
        context['success'] = 'Your email has been verified.'
        return redirect('custom_auth:verify_email_complete')
    else:
        context['fail'] = 'The link is invalid..'

    return render(request, 'custom_auth/verify_email_confirm.html', context)


def verify_email(request):
    if request.method == "POST" and not request.user.email_is_verified:
        if not request.user.email_is_verified:
            current_site = get_current_site(request)
            user = request.user
            user.is_active = False
            email = request.user.email
            subject = 'Verify your email!'
            message = render_to_string('custom_auth/verification_email.html', {
                'request': request,
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

            email = EmailMessage(
                subject=subject,
                body=message, to=[email],
                from_email='fhbxdfh.dhncdtb@gmail.com'
            )

            email.content_subtype = 'html'
            email.send()

            return redirect('custom_auth:verify_email_success')
        else:
            redirect('custom_auth:signup')

    return render(request, 'custom_auth/verify_email.html')


class CustomUserCreationView(FormView):
    form_class = CustomUserCreationForm
    template_name = 'custom_auth/signup.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        user.is_active = False
        login(self.request, user)

        if not user.email_is_verified:
            return redirect(reverse_lazy('custom_auth:verify_email'))

        if user is not None and user.is_active:
            return redirect(reverse_lazy('main:home'))

        return super().form_valid(form)

    def clean_email(self):
        email_input = self.cleaned_data.get('email')

        if CustomUser.objects.filter(email=email_input).exists():
            raise forms.ValidationError('Email already exists! Please other email.')

        return email_input


class CustomUserLoginView(FormView):
    form_class = CustomUserLoginForm
    template_name = 'custom_auth/login.html'
    redirect_authenticated_user = True
    success_url = reverse_lazy('main:home')

    def form_valid(self, form):
        credentials = form.cleaned_data

        if not CustomUser.objects.filter(email=credentials['email']).exists():
            return redirect('custom_auth:login')

        credentials['username'] = CustomUser.objects.get(email=credentials['email']).username

        user = authenticate(username=credentials['username'], email=credentials['email'],
                            password=credentials['password'])

        if user is not None and user.is_active:
            login(self.request, user)
            return redirect('main:home')
        else:
            return redirect('custom_auth:login')


class CustomUserProfileView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'custom_auth/user_profile.html'
    context_object_name = 'user'

    def get_object(self, queryset=None):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bookings'] = CarBooking.objects.filter(customer=self.request.user)

        return context


def LogoutView(request):
    logout(request)
    return redirect(reverse_lazy('main:home'))

vehicle_rental/custom_auth/templates/custom_auth/login.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
Login Page
{% endblock title %}

{% block content %}

<div>
<a onclick="history.back()" style="position: relative; top: 51px; left: 215px;"><button type="button" class="btn btn-outline-warning">Back</button></a>
<div class="container" style="display: block; text-align: center;">
    <form method="post" class="login-form mt-5" style="width: 750px; display: inline-block; margin-left: auto; margin-right: auto; text-align: left;">
      {% csrf_token %}
      <div class="lq2-text-component lq2-text-center lq2-margin-bottom-sm" >
        <h1 style="color: #ffbd00">Log in</h1>
        <p style="color: #fcda7c">Enter the required data to login.</p>
          {% for error in errors %}
          {{ error }}
          {% empty %}
          {% endfor %}
      </div>

      <div class="lq2-grid lq2-gap-xs">
<!--        Login with facebook -->
<!--        <div class="lq2-col-6@xs">-->
<!--          <a href="#">-->
<!--            <button class="lq2-btn lq2-btn&#45;&#45;subtle lq2-width-100%">-->
<!--              <svg aria-hidden="true" class="lq2-icon lq2-margin-right-3xs" viewBox="0 0 16 16"><g><path d="M16,3c-0.6,0.3-1.2,0.4-1.9,0.5c0.7-0.4,1.2-1,1.4-1.8c-0.6,0.4-1.3,0.6-2.1,0.8c-0.6-0.6-1.5-1-2.4-1 C9.3,1.5,7.8,3,7.8,4.8c0,0.3,0,0.5,0.1,0.7C5.2,5.4,2.7,4.1,1.1,2.1c-0.3,0.5-0.4,1-0.4,1.7c0,1.1,0.6,2.1,1.5,2.7 c-0.5,0-1-0.2-1.5-0.4c0,0,0,0,0,0c0,1.6,1.1,2.9,2.6,3.2C3,9.4,2.7,9.4,2.4,9.4c-0.2,0-0.4,0-0.6-0.1c0.4,1.3,1.6,2.3,3.1,2.3 c-1.1,0.9-2.5,1.4-4.1,1.4c-0.3,0-0.5,0-0.8,0c1.5,0.9,3.2,1.5,5,1.5c6,0,9.3-5,9.3-9.3c0-0.1,0-0.3,0-0.4C15,4.3,15.6,3.7,16,3z"></path></g></svg>-->
<!--              <span>Login with Twitter</span>-->
<!--            </button>-->
<!--          </a>-->
<!--        </div>-->

<!--        <div class="lq2-col-6@xs">-->
<!--          <a href="">-->
<!--            <button class="lq2-btn lq2-btn&#45;&#45;subtle lq2-width-100%">-->
<!--              <svg aria-hidden="true" class="lq2-icon lq2-margin-right-3xs" viewBox="0 0 16 16"><g><path d="M16,8.048a8,8,0,1,0-9.25,7.9V10.36H4.719V8.048H6.75V6.285A2.822,2.822,0,0,1,9.771,3.173a12.2,12.2,0,0,1,1.791.156V5.3H10.554a1.155,1.155,0,0,0-1.3,1.25v1.5h2.219l-.355,2.312H9.25v5.591A8,8,0,0,0,16,8.048Z"></path></g></svg>-->
<!--              <span>Login with Facebook</span>-->
<!--            </button>-->
<!--          </a>-->
<!--        </div>-->
      </div>

      <div class="lq2-margin-bottom-sm">
        <label class="lq2-form-label lq2-margin-bottom-3xs" for="input-email" style="color: #fcda7c">Email</label>
        {{ form.email }}
      </div>

      <div class="lq2-margin-bottom-sm">
        <div class="lq2-flex lq2-justify-between lq2-margin-bottom-3xs">
          <label class="lq2-form-label" for="input-password" style="color: #fcda7c">Password</label>
          <span class="lq2-text-sm"><a href="{% url 'custom_auth:reset_password' %}" style="color: white">Forgot?</a></span>
        </div>
        {{ form.password }}
      </div>

      <div class="lq2-margin-bottom-sm">
        <button class="lq2-btn lq2-btn--primary lq2-btn--md lq2-width-100%" style="background: #ffbd00; font-weight: 700; font-size: 27.5px;"><input class="button" type="submit" value="">Login</button>
      </div>

      <div class="lq2-text-center">
        <p class="lq2-text-sm" style="color: #fcda7c">Don't have an account? <a href="{% url 'custom_auth:signup' %}" style="color: white">Get started</a></p>
      </div>
    </form>
</div>
</div>

<style>
 /* --------------------------------

File#: _1_login-form
Title: Login Form
Descr: Login form template
Usage: codyhouse.co/license

-------------------------------- */
/* reset */
*, *::after, *::before {
  box-sizing: border-box;
}

* {
  font: inherit;
  margin: 0;
  padding: 0;
  border: 0;
}

body {
  background-color: hsl(0, 0%, 100%);
  font-family: system-ui, sans-serif;
  color: hsl(230, 7%, 23%);
  font-size: 1rem;
}

h1, h2, h3, h4 {
  line-height: 1.2;
  color: white;
  font-weight: 700;
}

h1 {
  font-size: 2.0736rem;
}

h2 {
  font-size: 1.728rem;
}

h3 {
  font-size: 1.25rem;
}

h4 {
  font-size: 1.2rem;
}

ol, ul, menu {
  list-style: none;
}

button, input, textarea, select {
  background-color: transparent;
  border-radius: 0;
  color: inherit;
  line-height: inherit;
  appearance: none;
}

textarea {
  resize: vertical;
  overflow: auto;
  vertical-align: top;
}

a {
  color: hsl(250, 84%, 54%);
}

table {
  border-collapse: collapse;
  border-spacing: 0;
}

img, video, svg {
  display: block;
  max-width: 100%;
}

@media (min-width: 64rem) {
  body {
    font-size: 1.25rem;
  }

  h1 {
    font-size: 3.051rem;
  }

    h2 {
    font-size: 2.44rem;
  }

    h3 {
    font-size: 1.75rem;
  }

    h4 {
    font-size: 1.5625rem;
  }
}

/* variables */
:root {
  /* colors */
  --lq2-color-primary-hsl: 250, 84%, 54%;
  --lq2-color-bg-hsl: 0, 0%, 100%;
  --lq2-color-contrast-high-hsl: 230, 7%, 23%;
  --lq2-color-contrast-higher-hsl: 230, 13%, 9%;
  --lq2-color-bg-dark-hsl: 240, 4%, 95%;
  --lq2-color-white-hsl: 0, 0%, 100%;
  --lq2-color-primary-darker-hsl: 250, 84%, 38%;
  --lq2-color-primary-light-hsl: 250, 84%, 60%;
  --lq2-color-bg-lighter-hsl: 0, 0%, 100%;
  --lq2-color-black-hsl: 230, 13%, 9%;
  --lq2-color-bg-light-hsl: 0, 0%, 100%;
  --lq2-color-contrast-lower-hsl: 240, 4%, 85%;
  --lq2-color-contrast-low-hsl: 240, 4%, 65%;
  --lq2-color-accent-hsl: 342, 89%, 48%;

  /* spacing */
  --lq2-space-3xs: 0.25rem;
  --lq2-space-xs: 0.5rem;
  --lq2-space-sm: 0.75rem;
  --lq2-space-2xs: 0.375rem;
  --lq2-space-md: 1.25rem;

  /* typography */
  --lq2-text-sm: 0.833rem;
  --lq2-text-sm: 0.833rem;
}

@media(min-width: 64rem){
  :root {
    /* spacing */
    --lq2-space-3xs: 0.375rem;
    --lq2-space-xs: 0.75rem;
    --lq2-space-sm: 1.125rem;
    --lq2-space-2xs: 0.5625rem;
    --lq2-space-md: 2rem;

    /* typography */
    --lq2-text-sm: 1rem;
    --lq2-text-sm: 1rem;
  }
}

/* buttons */
.lq2-btn {
  position: relative;
  display: inline-flex;
  justify-content: center;
  align-items: center;
  font-size: 1em;
  white-space: nowrap;
  text-decoration: none;
  background: hsl(var(--lq2-color-bg-dark-hsl));
  color: hsl(var(--lq2-color-contrast-higher-hsl));
  cursor: pointer;
  text-decoration: none;
  line-height: 1.2;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  transition: all 0.2s ease;
  will-change: transform;
  padding: var(--lq2-space-2xs) var(--lq2-space-sm);
  border-radius: 0.25em;
}

.lq2-btn:focus-visible {
  box-shadow: 0px 0px 0px 2px hsl(var(--lq2-color-bg-hsl)), 0px 0px 0px 4px hsla(var(--lq2-color-contrast-higher-hsl), 0.15);
  outline: none;
}

.lq2-btn:active {
  transform: translateY(2px);
}

.lq2-btn--primary {
  background: hsl(var(--lq2-color-primary-hsl));
  color: hsl(var(--lq2-color-white-hsl));
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.15), 0px 1px 3px hsla(var(--lq2-color-primary-darker-hsl), 0.25), 0px 2px 6px hsla(var(--lq2-color-primary-darker-hsl), 0.1), 0px 6px 10px -2px hsla(var(--lq2-color-primary-darker-hsl), 0.25);
}

.lq2-btn--primary:hover {
  background: hsl(var(--lq2-color-primary-light-hsl));
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.15), 0px 1px 2px hsla(var(--lq2-color-primary-darker-hsl), 0.25), 0px 1px 4px hsla(var(--lq2-color-primary-darker-hsl), 0.1), 0px 3px 6px -2px hsla(var(--lq2-color-primary-darker-hsl), 0.25);
}

.lq2-btn--primary:focus {
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.15), 0px 1px 2px hsla(var(--lq2-color-primary-darker-hsl), 0.25), 0px 1px 4px hsla(var(--lq2-color-primary-darker-hsl), 0.1), 0px 3px 6px -2px hsla(var(--lq2-color-primary-darker-hsl), 0.25), 0px 0px 0px 2px hsl(var(--lq2-color-bg-hsl)), 0px 0px 0px 4px hsl(var(--lq2-color-primary-hsl));
}

.lq2-btn--subtle {
  background: hsl(var(--lq2-color-bg-lighter-hsl));
  color: hsl(var(--lq2-color-contrast-higher-hsl));
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.1), 0px 0px 0px 1px hsla(var(--lq2-color-black-hsl), 0.02), 0px 1px 3px -1px hsla(var(--lq2-color-black-hsl), 0.2), 0 0.3px 0.4px rgba(0, 0, 0, 0.025),0 0.9px 1.5px rgba(0, 0, 0, 0.05), 0 3.5px 6px rgba(0, 0, 0, 0.1);
}

.lq2-btn--subtle:hover {
  background: hsl(var(--lq2-color-bg-light-hsl));
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.1), 0px 0px 0px 1px hsla(var(--lq2-color-black-hsl), 0.02), 0px 1px 3px -1px hsla(var(--lq2-color-black-hsl), 0.2), 0 0.1px 0.3px rgba(0, 0, 0, 0.06),0 1px 2px rgba(0, 0, 0, 0.12);
}

.lq2-btn--subtle:focus {
  box-shadow: inset 0px 1px 0px hsla(var(--lq2-color-white-hsl), 0.1), 0px 0px 0px 1px hsla(var(--lq2-color-black-hsl), 0.02), 0px 1px 3px -1px hsla(var(--lq2-color-black-hsl), 0.2), 0 0.1px 0.3px rgba(0, 0, 0, 0.06),0 1px 2px rgba(0, 0, 0, 0.12), 0px 0px 0px 2px hsl(var(--lq2-color-bg-hsl)), 0px 0px 0px 4px hsl(var(--lq2-color-contrast-high-hsl));
}

.lq2-btn--md {
  font-size: 1.2em;
}

/* form elements */
.lq2-form-control {
  font-size: 1em;
  padding: var(--lq2-space-2xs) var(--lq2-space-xs);
  background: hsl(var(--lq2-color-bg-dark-hsl));
  line-height: 1.2;
  box-shadow: inset 0px 0px 0px 1px hsl(var(--lq2-color-contrast-lower-hsl));
  transition: all 0.2s ease;
  border-radius: 0.25em;
}

.lq2-form-control::placeholder {
  opacity: 1;
  color: hsl(var(--lq2-color-contrast-low-hsl));
}

.lq2-form-control:focus, .lq2-form-control:focus-within {
  background: hsl(var(--lq2-color-bg-hsl));
  box-shadow: inset 0px 0px 0px 1px hsla(var(--lq2-color-contrast-lower-hsl), 0), 0px 0px 0px 2px hsl(var(--lq2-color-primary-hsl)), 0 0.3px 0.4px rgba(0, 0, 0, 0.025),0 0.9px 1.5px rgba(0, 0, 0, 0.05), 0 3.5px 6px rgba(0, 0, 0, 0.1);
  outline: none;
}

.lq2-form-label {
  display: inline-block;
  font-size: var(--lq2-text-sm);
}

/* icons */
.lq2-icon {
  height: var(--lq2-size, 1em);
  width: var(--lq2-size, 1em);
  display: inline-block;
  color: inherit;
  fill: currentColor;
  line-height: 1;
  flex-shrink: 0;
  max-width: initial;
}

/* component */


/* utility classes */
.lq2-text-sm {
  font-size: var(--lq2-text-sm);
}

.lq2-text-center {
  text-align: center;
}

.lq2-width-100\% {
  width: 100%;
}

.lq2-margin-bottom-sm {
  margin-bottom: var(--lq2-space-sm);
}

.lq2-margin-bottom-3xs {
  margin-bottom: var(--lq2-space-3xs);
}

.lq2-justify-between {
  justify-content: space-between;
}

.lq2-flex {
  display: flex;
}

.lq2-margin-y-sm {
  margin-top: var(--lq2-space-sm);
  margin-bottom: var(--lq2-space-sm);
}

.lq2-margin-right-3xs {
  margin-right: var(--lq2-space-3xs);
}

.lq2-gap-xs {
  gap: var(--lq2-space-xs);
}

.lq2-grid {
  display: grid;
  grid-template-columns: repeat(12, 1fr);
}

.lq2-grid > * {
  min-width: 0;
  grid-column-end: span 12;
}

.lq2-text-component :where(h1, h2, h3, h4) {
  line-height: var(--lq2-heading-line-height, 1.2);
  margin-top: calc(var(--lq2-space-md) * var(--lq2-space-multiplier, 1));
  margin-bottom: calc(var(--lq2-space-sm) * var(--lq2-space-multiplier, 1));
}

.lq2-text-component :where(p, blockquote, ul li, ol li) {
  line-height: var(--lq2-body-line-height, 1.4);
}

.lq2-text-component :where(ul, ol, p, blockquote, .lq2-text-component__block) {
  margin-bottom: calc(var(--lq2-space-sm) * var(--lq2-space-multiplier, 1));
}

.lq2-text-component :where(ul, ol) {
  padding-left: 1.25em;
}

.lq2-text-component ul :where(ul, ol), .lq2-text-component ol :where(ul, ol) {
  padding-left: 1em;
  margin-bottom: 0;
}

.lq2-text-component ul {
  list-style-type: disc;
}

.lq2-text-component ol {
  list-style-type: decimal;
}

.lq2-text-component img {
  display: block;
  margin: 0 auto;
}

.lq2-text-component figcaption {
  margin-top: calc(var(--lq2-space-xs) * var(--lq2-space-multiplier, 1));
  font-size: var(--lq2-text-sm);
  text-align: center;}

.lq2-text-component em {
  font-style: italic;
}

.lq2-text-component strong {
  font-weight: bold;
}

.lq2-text-component s {
  text-decoration: line-through;
}

.lq2-text-component u {
  text-decoration: underline;
}

.lq2-text-component mark {
  background-color: hsla(var(--lq2-color-accent-hsl), 0.2);
  color: inherit;
}

.lq2-text-component blockquote {
  padding-left: 1em;
  border-left: 4px solid hsl(var(--lq2-color-contrast-lower-hsl));
  font-style: italic;
}

.lq2-text-component hr {
  margin: calc(var(--lq2-space-md) * var(--lq2-space-multiplier, 1)) auto;
  background: hsl(var(--lq2-color-contrast-lower-hsl));
  height: 1px;
}

.lq2-text-component > *:first-child {
  margin-top: 0;
}

.lq2-text-component > *:last-child {
  margin-bottom: 0;
}

.lq2-text-component.lq2-line-height-xs {
  --lq2-heading-line-height: 1;
  --lq2-body-line-height: 1.1;
}

.lq2-text-component.lq2-line-height-sm {
  --lq2-heading-line-height: 1.1;
  --lq2-body-line-height: 1.2;
}

.lq2-text-component.lq2-line-height-md {
  --lq2-heading-line-height: 1.15;
  --lq2-body-line-height: 1.4;
}

.lq2-text-component.lq2-line-height-lg {
  --lq2-heading-line-height: 1.22;
  --lq2-body-line-height: 1.58;
}

.lq2-text-component.lq2-line-height-xl {
  --lq2-heading-line-height: 1.3;
  --lq2-body-line-height: 1.72;
}

@media(min-width: 32rem){
  .lq2-col-6\@xs {
    grid-column-end: span 6;
  }
}
</style>
{% endblock content %}

vehicle_rental/custom_auth/templates/custom_auth/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'custom_auth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}